### ISSUE TITLE
[BUG] Unable to get key `username` out of TOML file.

### ISSUE THREAD

**Issue by davidkurilla** [davidkurilla/refuel#13]
When testing `refuel` in the `hyperswitch` environment, the TOML parser is unable to retrieve the key `username` from the TOML file. We know that it is able to find and open the file provided. We think that this is because the TOML files we used for testing did not include a proper table header but the file we are using in `hyperswitch` does.

**Proposed Solution**
Restructure the TOML parser so that it searches for the keys `username`, `password`, and `dbname` underneath a table with a heading called `[master_database]`.

The TOML file used for testing should look something like this:
```toml
[master_database]
username = "db_user"
password = "db_pass"
dbname = "db_name"
```
